apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: ingress
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result[0] > 0.90
      provider:
        prometheus:
          address: "https://XXXXXXXXXX.chronosphere.io/data/metrics/"
          timeout: 5 # timeout is expressed in seconds
          headers:
            - key: Authorization
              value: "Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
          query: >+
            sum(
              rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",status!~"[4-5].*"}[5m]))
              /
              sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}"}[5m])
            )
